#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#5A8E3A'

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

#hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-e quit
hc keybind $Mod-Shift-r reload
#hc keybind $Mod-Shift-c close
hc keybind $Mod-Shift-q close
TERMINAL=urxvt
hc keybind $Mod-Return spawn ${TERMINAL:-xterm} # use your $TERMINAL with xterm as fallback

# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05

hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Down 		resize down +$resizestep
hc keybind $Mod-Up   		resize up +$resizestep
hc keybind $Mod-Right 		resize right +$resizestep

# tags

: <<EOF

tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

EOF

# cycle through tags
#hc keybind $Mod-period use_index +1 --skip-visible
#hc keybind $Mod-comma  use_index -1 --skip-visible
hc keybind $Mod-bracketleft  use_index -1 --skip-visible
hc keybind $Mod-bracketright  use_index +1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#345F0C'
hc set frame_border_width 1
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 5
hc set frame_gap 4

hc attr theme.active.color '#9fbc00'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color orange
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color '#141414'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done

#hc keybind $Mod-d spawn dmenu_run_hlwm
#hc keybind $Mod-grave spawn j4-dmenu-desktop

hc keybind $Mod-d spawn rofi -combi-modi drun,run -show combi

# tags

key="1"
name="1: Qutebrowser"
hc rename default "$name"
#hc add "$name"
hc keybind "$Mod-$key" use "$name"
hc keybind "$Mod-Shift-$key" move "$name"

key="2"
name="2: Spacemacs"
hc add "$name"
hc keybind "$Mod-$key" use "$name"
hc keybind "$Mod-Shift-$key" move "$name"

key="3"
name="3: Ranger"
hc add "$name"
hc keybind "$Mod-$key" use "$name"
hc keybind "$Mod-Shift-$key" move "$name"

key="4"
name="4: Weechat"
hc add "$name"
hc keybind "$Mod-$key" use "$name"
hc keybind "$Mod-Shift-$key" move "$name"

key="5"
name="5: Newsbeuter"
hc add "$name"
hc keybind "$Mod-$key" use "$name"
hc keybind "$Mod-Shift-$key" move "$name"

key="6"
name="6: MPD"
hc add "$name"
hc keybind "$Mod-$key" use "$name"
hc keybind "$Mod-Shift-$key" move "$name"

key="7"
name="7: Mutt"
hc add "$name"
hc keybind "$Mod-$key" use "$name"
hc keybind "$Mod-Shift-$key" move "$name"

key="8"
name="8: Gitter"
hc add "$name"
hc keybind "$Mod-$key" use "$name"
hc keybind "$Mod-Shift-$key" move "$name"

key="9"
name="9: Other"
hc add "$name"
hc keybind "$Mod-$key" use "$name"
hc keybind "$Mod-Shift-$key" move "$name"

key="0"
name="10: Fish"
hc add "$name"
hc keybind "$Mod-$key" use "$name"
hc keybind "$Mod-Shift-$key" move "$name"

: << 'END'

key="minus"
name="11: Music"
hc add "$name"
hc keybind "$Mod-$key" use "$name"
hc keybind "$Mod-Shift-$key" move "$name"

# plus doesn't work
key="equal"
name="12: Web"
hc add "$name"
hc keybind "$Mod-$key" use "$name"
hc keybind "$Mod-Shift-$key" move "$name"

END

hc keybind "$Mod-period" spawn hlwm-layout-manager load

# setting lockscreen wallpaper
# i3lock doesn't support JPG, only PNG

hc keybind "Mod1-l" spawn i3lock --color=87ceeb --image "$HOME/Tengerid Lockscreen.png"
hc keybind "Mod1-b" spawn i3lock --color=87ceeb --image "$HOME/SatanicBear.png"
hc keybind "Mod1-v" spawn i3lock --color=87ceeb --image "$HOME/img/VikingWall.png"
hc keybind "Mod1-g" spawn i3lock --color=87ceeb --image "$HOME/img/RedGoat.png"

# %b abbr month name, %a abbr weekday name
hc keybind Print spawn scrot '%a-%d-%b-%M-%S.png' -e 'mv $f /home/chinggis/Screenshots/'
# no --release in hlwm :(
hc keybind Shift-Print spawn bash -c 'sleep 0.1 ; scrot -s'

# Start applications

hc spawn xinput --disable "ETPS/2 Elantech Touchpad"

hc spawn dunst

hc spawn redshift

hc spawn feh --bg-scale "$HOME/Tengerid Wallpaper.png"

hc spawn notify-send "Welcome to Arch Linux!"

# for the hate of brightness
hc spawn brightness
# and for the hate of blinking cursors
hc spawn cursor

#hc spawn qutebrowser --backend webengine
#hc spawn urxvt -e ranger
#hc spawn urxvt
#hc spawn urxvt -e cmus

# Set keyboard layouts
hc spawn setxkbmap -layout "us,az,ru" -option "grp:alt_shift_toggle"

# Disable blank screen 
hc spawn xset -dpms
